version: '2.1'
services:
  configserver:
    image: uaparts/configserver:0.0.1-SNAPSHOT
    ports:
      - "8071:8071"
    healthcheck:
      test: "exit 0"
      interval: 10s
      timeout: 5s
    networks:
      backend:
        aliases:
          - "configserver"
  gateway:
    image: uaparts/gateway:0.0.1-SNAPSHOT
    ports:
      - "8072:8072"
    environment:
      PROFILE: "default"
      SERVER_PORT: "8072"
      CONFIGSERVER_URI: "http://configserver:8071"
      EUREKASERVER_URI: "http://eurekaserver:8761/eureka/"
      EUREKASERVER_PORT: "8761"
      CONFIGSERVER_PORT: "8071"
    depends_on:
      eurekaserver:
        condition: service_started
    networks:
      backend:
        aliases:
          - "gateway"

  eurekaserver:
    image: uaparts/eurekaserver:0.0.1-SNAPSHOT
    ports:
      - "8761:8761"
    networks:
      backend:
        aliases:
          - "eurekaserver"
volumes:
  postgres:
networks:
  backend:
    driver: bridge
